spring:
  config:
    activate:
      on-profile: prod

  application:
    name: makar

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    sql:
      init:
        platform: mysql

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #          dialect: org.hiberante.dialect.MySQL8Dialect

  logging.level:
    org.hibernate.SQL: debug